name: learn-github-actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
      - uses: actions/checkout@v4
      - run: echo hello world
        name: Run echo command
      - run : find .
        name: List files


